config/routes.rb
Rails.application.routes.draw do

  get 'errors_controller/show'

  root 'pages#index'

  get 'admin/settings' => 'admin/settings#show'

  namespace 'admin' do
    resource 'settings', :only => [:edit, :update, :show, :destroy]
  end

  resources 'admin' do
    resources 'users', :shallow => true
  end

  get 'log_out' => 'sessions#destroy', :as => 'log_out'

  get 'log_in' => 'sessions#new', :as => 'log_in'

  get 'sign_up' => 'users#new', :as => 'sign_up'

  get 'login' => 'session#new'

  resource 'sessions', :path => 'log_in'
  resources 'pages'

end

app/models/page.rb
require 'redcarpet'

class Page < ActiveRecord::Base

  validates :title, :uniqueness => true, :presence => true

  before_save :create_slug

  def self.open(slug)
    Page.find_by_slug(slug)
  end

  def to_param
    slug
  end

  private

  def create_slug
    write_attribute(:slug, title.split.join("_").parameterize)
  end
end

app/models/settings.rb
class Settings < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_create :create_remember_token

  validates :email, :uniqueness => true, :presence => true

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token) 
  end
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < AdminController
  def show
    @settings = Settings.first
  end

  def edit
    @settings = Settings.first
  end

  def destroy
    @settings = Settings.first
    @settings.destroy
    # Do you really want to break everything?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index

  end

  def create

  end

  def edit

  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authorize_admin

  private

  def authorize_admin
    unless current_user.admin?
      redirect_to pages_path, :alert => "You are not permitted to do that."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to log_in_url, alert: "Please log in." if current_user.nil?
  end
end

app/controllers/controller_controller.rb
class ControllerController < ApplicationController
  def admin/users
  end

  def index
  end

  def create
  end

  def edit
  end
end

app/controllers/pages_controller.rb
require 'active_support/inflector'
require_relative '../decorators/markdown_decorator'

class PagesController < ApplicationController
  before_filter :authorize

  def index
    @pages = MarkdownDecorator.decorate(Page.all)
  end

  def show
    @page = MarkdownDecorator.decorate(Page.open(params[:id]))
    unless @page.model?
      @title = ActiveSupport::Inflector.titleize(params[:id])
      render :non_existent
    end
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      flash[:notice] = "Page was successfully created."
      render :show
    else
      render :edit
    end
  end

  def edit
    @page = Page.open(params[:id])
  end

  def update
    @page = Page.open(params[:id])

    if @page.update(page_params)
      redirect_to page_path @page
    else
      render 'edit'
    end
  end

  def new
    @title = params[:title] || ""
    @page = Page.new
  end

  def destroy
    @page = Page.open(params[:id])
    if @page.destroy
      flash[:notice] = %Q{ "#{@page.title}" was successfully deleted.}
      redirect_to pages_path
    else
      flash[:notice] = "An error prevented this page from being deleted."
    end
  end

  private

  def page_params
    params.require(:page).permit(:title, :body, :id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(user_params[:email])
    if user && user.authenticate(user_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
      if user_params[:remember_me] == "1"
        remember_token = User.new_remember_token
        cookies.permanent[:remember_token]
        user.update_attribute(:remember_token)
      end
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to log_in_path, :notice => "Logged out!"
  end

  private

  def user_params
    params.permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to edit_user_path @user, :notice => "You are signed up!"
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id]) 
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "Your user information was successfully updated."
      redirect_to edit_user_path @user
    else
      render edit_user_path @user
    end
  end

  private

  def user_params
    params.require(:user).permit(:id,
                                 :first_name,
                                 :last_name,
                                 :password,
                                 :email,
                                 :password_confirmation,
                                 :admin)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controller_helper.rb
module ControllerHelper
end

app/helpers/errors_controller_helper.rb
module ErrorsControllerHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/settings/edit.html.erb
<h1>Settings</h1>

<%= form_for @settings, :id => 'admin_form'  do |f| %>
  <% if @page.errors.any? %>
    <div class="error_messages">
      <h2>Page is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label "Wiki name" %>
  <%= f.text_field :name %>
<% end %>

app/views/admin/settings/show.html.erb
<section id="settings">

<h1>Settings</h1>

<%= @settings.name %>
</section>

app/views/controller/admin/users.html.erb
<h1>Controller#admin/users</h1>
<p>Find me in app/views/controller/admin/users.html.erb</p>

app/views/controller/create.html.erb
<h1>Controller#create</h1>
<p>Find me in app/views/controller/create.html.erb</p>

app/views/controller/edit.html.erb
<h1>Controller#edit</h1>
<p>Find me in app/views/controller/edit.html.erb</p>

app/views/controller/index.html.erb
<h1>Controller#index</h1>
<p>Find me in app/views/controller/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ohwiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/header' %>

<% if !flash.empty? %>
  <div id="flash">
    <% flash.keys.each do |k| %>
      <div class="<%= k %>">
        <%= flash[k] %>
      </div>
    <% end %>
  </div>
<% end %>

<%= yield %>

  </body>
  </html>

app/views/pages/create.html.erb
<h1>Page#create</h1>
<p>Find me in app/views/page/create.html.erb</p>

app/views/pages/destroy.html.erb
<h1>Page#destroy</h1>
<p>Find me in app/views/page/destroy.html.erb</p>

app/views/pages/edit.html.erb
<%= form_for :page, :url => page_path(@page), :method => :patch do |f| %>
  <% if @page.errors.any? %>
    <div class="error_messages">
      <h2>Page is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit :value => 'Save changes', :id => 'submit' %>
<% end %>

app/views/pages/index.html.erb
<%= render 'shared/edit_menu' %>

<section id="recent-pages">
  <h1>Recent Pages</h1>
  <ul>
    <% @pages.each do |p| %>
      <li class="page-listing">
        <%= link_to p.title, '/pages/' + p.to_param %>
        <%= render :partial => 'shared/action_menu', :locals => {:p => p } %>
      </li>
    <% end %>
  </ul>
</section><!-- recent pages -->

app/views/pages/new.html.erb
<h1>Create new page</h1>

<%= form_for @page do |f| %>
  <% if @page.errors.any? %>
    <div class="error_messages">
      <h2>Page is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title, :value => @title %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit :value => 'Create page', :id => 'submit' %>
<% end %>

app/views/pages/non_existent.html.erb
<h1><cite><%= @title %></cite> doesn't exist yet. <%= link_to 'Create it?', new_page_path(:title => @title), :class => 'create-non-existent' %></h1>

app/views/pages/show.html.erb
<%= render 'shared/edit_menu', :locals => {:page => @page} %>
<article>
  <header>
    <h1>Title: <%= @page.title %></h1>
  </header>
  <%= @page.body %>
</article>


app/views/shared/_action_menu.html.erb
<menu class="action">
  <%= link_to 'Edit', edit_page_path(p) %>
  <%= link_to 'Delete', page_path(p),
    :method => :delete, :data => { confirm: 'Are you sure?' },
    :id => p.to_param %>
</menu>

app/views/shared/_edit_menu.html.erb
<menu id="edit">
  <ul>
    <% if @page %>
      <li><%= link_to 'Edit this page', edit_page_path(@page) %></li>
    <% end %>
    <li><%= link_to 'Add new page', new_page_path %></li>
  <ul>
</menu><!-- edit menu -->

app/views/shared/_header.html.erb
<header id="main_header">
  <h1><%= link_to 'OhWiki', pages_path %></h1>
  <% if current_user %>
    <menu id="user_menu">
      <li><%= link_to "Profile", edit_user_path(current_user.id), :id => "profile_link" %>
    </li>
      <li><%= link_to 'Log out', log_out_path(current_user.id) %></li>
    </menu><!-- nav -->
  <% end %>
</header>

app/views/shared/_nav_menu.html.erb
<header>
  <h1>OhWiki</h1>
  <% if current_user %>
    <menu id="nav">
      <li><%= link_to 'Recent Pages', pages_path %></li>
      <li><%= link_to 'Profile', edit_user_path(current_user.id) %></li>
    </menu><!-- nav -->
  <% end %>
</header>

app/views/users/_user_form.html.erb
<section id="user_form">
  <%= form_for @user do |f| %>
    <fieldset name="General information">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <% if @user.admin? %>
        <label>Admin: <%= f.check_box :admin %></label>
      <% end %>

    </fieldset><!-- General Information -->

    <fieldset name="passord">
      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </fieldset>

    <%= f.submit :id => "submit" %>
  <% end %>
</section>

app/views/users/edit.html.erb
<%= render 'user_form', :locals => {:user => :@user} %>

app/views/users/new.html.erb
<h1>Create new user</h1>
<%= render 'user_form', :locals => {:user => :@user} %>

app/views/welcome/index.html.erb
<% if current_user %>
  <%= link_to 'Create page', new_page_path %>
<% else %>
  <%= link_to 'Please sign in to OhWiki', log_in_path %>
<% end %>